backend:
  name: git-gateway
  branch: main

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "products"
    label: "Товары"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Название", name: "title", widget: "string" }
      - { label: "Бренд", name: "brand", widget: "string" }
      - { label: "Цена", name: "price", widget: "number" }
      - { label: "Описание", name: "body", widget: "markdown" }